### ISSUE TITLE
Error when building cython module

### ISSUE THREAD

**Issue by Jumabek** [Eniac-Xie/faster-rcnn-resnet#15]
I am having following error when run 

` cd $ROOT/lib/
 make`

`C:\faster-rcnn-resnet\lib>make
python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 46, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME
make: *** [all] Error 1`

**Comment by gongxijun** [comment]
hi man , you should make sure you have been installed the cuda/cudnn driver@Jumabek
