### ISSUE TITLE
ValueError: could not broadcast input array from shape (2,17100,1) into shape (17100,1)

### ISSUE THREAD

**Issue by zhuyanfang000** [Eniac-Xie/faster-rcnn-resnet#22]
who knows why?T-T  I'm crazy!
I0331 21:30:19.628304 16920 net.cpp:744] Ignoring source layer fc1000
I0331 21:30:19.628332 16920 net.cpp:744] Ignoring source layer prob
Solving...
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/omnisky/faster-rcnn-resnet-master/tools/../lib/fast_rcnn/train.py", line 160, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/omnisky/faster-rcnn-resnet-master/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/omnisky/faster-rcnn-resnet-master/tools/../lib/rpn/proposal_layer.py", line 122, in forward
    proposals = bbox_transform_inv(anchors, bbox_deltas)
  File "/home/omnisky/faster-rcnn-resnet-master/tools/../lib/fast_rcnn/bbox_transform.py", line 53, in bbox_transform_inv
    pred_boxes[:, 0::4] = pred_ctr_x - 0.5 * pred_w
ValueError: could not broadcast input array from shape (2,17100,1) into shape (17100,1)

**Comment by Microos** [comment]
you shall check your anchor numbers to see if they are consistent in related layers
