### ISSUE TITLE
 top[idx].reshape(1, self._num_classes * 4) IndexError: Index out of range

### ISSUE THREAD

**Issue by zhoupan9109** [Eniac-Xie/faster-rcnn-resnet#26]
My dataset calsses number is 5 and I change *.prototxt files into 5 classes number, I can get the train model. But when I run ./tools/demo.py -- net resnet50 , it runs with the error as follow:

Traceback (most recent call last): File "./tools/demo.py", line 283, in <module> 
net = caffe.Net(prototxt, caffemodel, caffe.TEST)
 File "/home/zhoupan/caffe/models/faster-rcnn-resnet/tools/../lib/roi_data_layer/layer.py", line 131, in setup
    top[idx].reshape(1, self._num_classes * 4)
IndexError: Index out of range

How can I solve this problem? Thank you very much!

**Comment by zhoupan9109** [comment]
I use the caffemodel is faster-rcnn-resnet50.

**Comment by wanggp01** [comment]
> My dataset calsses number is 5 and I change *.prototxt files into 5 classes number, I can get the train model. But when I run ./tools/demo.py -- net resnet50 , it runs with the error as follow:
> 
> Traceback (most recent call last): File "./tools/demo.py", line 283, in
> net = caffe.Net(prototxt, caffemodel, caffe.TEST)
> File "/home/zhoupan/caffe/models/faster-rcnn-resnet/tools/../lib/roi_data_layer/layer.py", line 131, in setup
> top[idx].reshape(1, self._num_classes * 4)
> IndexError: Index out of range
> 
> How can I solve this problem? Thank you very much!

I have the same error，do you have resolve this?
